apiVersion: v1
kind: Service
metadata:
  name: calculadora-service
spec:
  type: NodePort
  selector:
    app: calculadora
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
